'''
This is a script to populate the ipython namespace with all of the subsets of
interest when checking the rotation properties of the APOGEE'''
from functools import partial

import numpy as np
from astropy.table import vstack, Table
import matplotlib.pyplot as plt
import scipy

import read_catalog as catin
import catalog
import astropy_util as au
import sample_characterization as samp
import hrplots as hr

# This dictionary allows any objects which was generated by any of the splits
# to be reconstructed by subsamples.
gendict = {}

dr14 = catin.dr14_with_KIC_stelparms()

bad_dr14, warn_dr14, vsini_dr14, good_dr14 = catalog.split_by_ASPCAP_flags(dr14)
del(dr14)
gendict["dr14"] = ("bad_dr14", "warn_dr14", "vsini_dr14", "good_dr14")

# Including objects with the warn flag requires more thoughtfulness. For right
# now, let's just look at the good targets. 

#goodwarn_dr14 = vstack([warn_dr14, good_dr14])
#del(good_dr14)
#del(warn_dr14)
#gendict["dr14"] = ("bad_dr14", "goodwarn_dr14")

# To make things easier from the start, I want to have the APOGEE LOGGs as
# their own column.
good_dr14["LOGG_FIT"] = good_dr14["FPARAM"][:,1]

# Separate out the asteroseismic dwarfs as early as I can to get the full
# sample.
ast_dwarf, non_ast_dwarf = catalog.split_asteroseismic_dwarfs(
    good_dr14, "APOGEE_ID")
del(good_dr14)
gendict["good_dr14"] = ("ast_dwarf", "non_ast_dwarf")

# Don't really care about giants either.

kic_giants, kic_dwarfs = catalog.split_logg(
    non_ast_dwarf, 3.5, loggcol="logg")
apo_giants, apo_dwarfs = catalog.split_logg(
    non_ast_dwarf, 3.5, loggcol="LOGG_FIT")
del(non_ast_dwarf)
gendict["non_ast_dwarf"] = ("kic_giants", "kic_dwarfs")


# Split between hot and cool dwarfs

cool_kic_dwarfs, hot_kic_dwarfs = catalog.split_teff(kic_dwarfs, 6500)
cool_apo_dwarfs, hot_apo_dwarfs = catalog.split_teff(apo_dwarfs, 6500)
del(kic_dwarfs)
del(apo_dwarfs)
gendict["kic_dwarfs"] = ("cool_kic_dwarfs", "hot_kic_dwarfs")
gendict["apo_dwarfs"] = ("cool_apo_dwarfs", "hot_apo_dwarfs")

# Split up DLSBs
dlsb, nodlsb, unknown_dlsb = catalog.split_dlsb(
    cool_kic_dwarfs, apid_col="APOGEE_ID")
del(cool_kic_dwarfs)
gendict["cool_kic_dwarfs"] = ("dlsb", "nodlsb", "unknown_dlsb")

# But let's count known and unknown non-DLSBs together.
non_dlsb = vstack([nodlsb, unknown_dlsb])
del(nodlsb)
del(unknown_dlsb)
gendict["cool_kic_dwarfs"] = ("dlsb", "non_dlsb")


# Objects with detectable rotation.
bad_rot, nondet_rot, det_rot = catalog.split_vsini(non_dlsb, [-1, 7])
del(non_dlsb)
gendict["non_dlsb"] = ("bad_rot", "nondet_rot", "det_rot")

# Objects that are rapid rotators.

very_rapid, rapid, slow = catalog.split_spectroscopic_rapid_rotators(
    det_rot, det_rot["radius"], det_rot["VSINI"])
del(det_rot)
gendict["det_rot"] = ("very_rapid", "rapid", "slow")

def gen_samp(name):
    '''Function to generate the given sample objects which was broken down.'''
    try:
        return globals()[name]
    except KeyError:
        return vstack([gen_samp(ob) for ob in gendict[name]])

def HR_Param_Check():
    '''Check how logg and teff parameters match with each other.'''
    fulltable = gen_samp("good_dr14")
    dwarfs = gen_samp("cool_kic_dwarfs")

    # I want a 2x2 plot of the full HR diagram.
    hr.logg_teff_comparison_subsample(
        fulltable["logg"], fulltable["teff"], fulltable["LOGG_FIT"],
        fulltable["TEFF"], dwarfs["logg"], dwarfs["teff"], dwarfs["LOGG_FIT"],
        dwarfs["TEFF"], "KIC", "APOGEE") 

def KIC_APOGEE_Param_Diff():
    '''See trends in Teff and log(g) differences with Teff.'''
    fulltable = gen_samp("good_dr14")

    tempdiff = (fulltable["teff"] - fulltable["TEFF"]) / fulltable["teff"]
    loggdiff = fulltable["logg"] - fulltable["LOGG_FIT"]
    linex = [min(fulltable["teff"]), max(fulltable["teff"])]
    
    f, (ax1, ax2) = plt.subplots(nrows=1, ncols=2)

    ax1.plot(fulltable["teff"], tempdiff, ls="", marker="*")
    ax1.plot(linex, [0,0], ls="-", marker="", lw=2)
    ax1.set_xlabel("KIC Teff")
    ax1.set_ylabel("Fractional KIC - APOGEE Teff Difference")
    hr.invert_x_axis(ax1)
    ax2.plot(fulltable["teff"], loggdiff, ls="", marker="*")
    ax2.plot(linex, [0,0], ls="-", marker="", lw=2)
    ax2.set_xlabel("KIC Teff")
    ax2.set_ylabel("KIC - APOGEE Log(g) Difference")
    hr.invert_x_axis(ax2)

def rotation_dist():
    '''Plot the vsini distribution over Teff.'''
    full_samp = gen_samp("cool_kic_dwarfs")
    samp = full_samp[full_samp["VSINI"] > 0]

    linex = [min(samp["teff"]), max(samp["teff"])]

    plt.plot(samp["teff"], samp["VSINI"], ls="", marker="*")
    plt.plot(linex, [7, 7], ls="--", c="orange", marker="")
    plt.xlabel("KIC Teff")
    plt.ylabel("VSINI")
    hr.invert_x_axis()

    nbins = 20
    top_percent, edges, indices = scipy.stats.binned_statistic(
        samp["teff"], samp["VSINI"], statistic=lambda x: np.percentile(x, 66.7), 
        bins=nbins)
    median_percent, edges, indices = scipy.stats.binned_statistic(
        samp["teff"], samp["VSINI"], statistic=lambda x: np.percentile(x, 50.0), 
        bins=nbins)
    bottom_percent, edges, indices = scipy.stats.binned_statistic(
        samp["teff"], samp["VSINI"], statistic=lambda x: np.percentile(x, 33.3), 
        bins=nbins)
    
    midpoints = (edges[:-1]+edges[1:])/2
    plt.errorbar(midpoints, median_percent, yerr=[
        median_percent-bottom_percent, top_percent-median_percent], marker="o",
                 c="r", ls="", lw=2, zorder=3)
