from pathlib import Path

HOME_DIR = Path.home()
HEAD_DIR = HOME_DIR / "Binaries"

CASAGRANDE_TABLE_PATH = HEAD_DIR
CASAGRANDE_TABLE_4 = CASAGRANDE_TABLE_PATH / "Casagrande_10_Table_4.txt" 
CASAGRANDE_TABLE_5 = CASAGRANDE_TABLE_PATH / "Casagrande_10_Table_5.txt"

DSEP_OUTPUT = HEAD_DIR / "DSEP"

DSEP_PATH = HOME_DIR / "DSep"
DSEP_ISOCHRONES= DSEP_PATH / "isochrones"
DSEP_INTERPOLATOR_EXECUTABLE = DSEP_PATH / "iso_interp_feh"
DSEP_SPLITTER_EXECUTABLE = DSEP_PATH / "isolf_split"
